'''Guess the number, between 0-100 '''

number = [0,1,2,3,4,5,6,7,8,9,10,11,12,\
        13,14,15,16,17,18,19,20,21,22,\
        23,24,25,26,27,28,29,30,31,32,\
        33,34,35,36,37,38,39,40,41,42,\
        43,44,45,46,47,48,49,50,51,52,\
        53,54,55,56,57,58,59,60,61,62,\
        63,64,65,66,67,68,69,70,71,72,\
        73,74,75,76,77,78,79,80,81,82,\
        83,84,85,86,87,88,89,90,91,92,\
        93,94,95,96,97,98,99,100]

def random():
    import random
    return random.choice(number)

def user_input():
    user_input_value = int(input("Guess the number:"))
    return user_input_value

def checker(stored_number,user_number):
    if user_number > 100 or user_number < 0:
        return f"User input invalid, number {user_number} outside range of 0-100."
    elif stored_number > user_number:
        return f"The random generated number is larger than the user inputed number which is {user_number}."
    
    elif stored_number < user_number:
        return f"The random generated number is smaller than the user inputed number which is {user_number}"

    elif stored_number == user_number:
        return f"You have guessed correctly, the random generated number {stored_number} equates to user inputed number {user_number}."
    else:
        return "None"
    
def main():
    print("This game is a number guesser, you have 10 tries to guess a number generated by a computer from 0 to 100, which must be an interger.")
    a = random()
    for c in range(10):
        b = user_input()
        print(checker(a,b))
    print("The program has ended")
main()
